Fix: add Cart Model. Issue#4 Still  WIP
Noorin99/HomeTaste pull request #15
Opened 2023-07-08 00:57 UTC by MOHAMMAD-ALMOHAMMAD

Finished The Cart Model, i will add the two other models tomorrow

2023-07-09 17:18 UTC, fatimaali200 requested changes
Good job Mohammad
-u must  use export before interfaces in case to use it .
-i think you should change the model name to order because it will be plural by mongoose.

2023-07-09 22:05 UTC, MOHAMMAD-ALMOHAMMAD commented
> Good job Mohammad -u must use export before interfaces in case to use it . -i think you should change the model name to order because it will be plural by mongoose.

@fatimaali200 , added a commit where i applied the requested changes, please take a look, and let me know if any further change is needed

2023-07-10 16:39 UTC, MOHAMMAD-ALMOHAMMAD commented
previously the userId property in both review.ts and cart.ts didnt reference the the userid in the User model, similarily dishId in review.ts also didnt reference the dish in the Food model, this is now fixed

2023-07-11 18:01 UTC, MasterOfAlune approved these changes

2023-07-11 18:16 UTC, fatimaali200 approved these changes

2023-07-11 19:13 UTC, merged