Feat: update save google function
Noorin99/HomeTaste pull request #27
Opened 2023-07-14 18:28 UTC by fatimaali200

![saveNewUserFromGoogle](https://github.com/Noorin99/HomeTaste/assets/79793662/f2f5cdce-7f7c-458f-ad38-0482aa7053c4)

![userAlreadyExists](https://github.com/Noorin99/HomeTaste/assets/79793662/46a0d6b8-b118-4259-8459-2d94ce059c00)
![db](https://github.com/Noorin99/HomeTaste/assets/79793662/c1a38b94-a23e-4737-911b-ef927cdd6a07)

2023-07-14 19:18 UTC, MOHAMMAD-ALMOHAMMAD requested changes
In the saveGoogle function you wrote, please remove `await newUser.save()` because it is not neceasary, you already called the `User.create()` method which automatically inserts + saves the user to the database

2023-07-15 08:38 UTC, Noorin99 approved these changes

2023-07-15 09:57 UTC, MasterOfAlune approved these changes

2023-07-15 10:12 UTC, MOHAMMAD-ALMOHAMMAD approved these changes

2023-07-15 10:13 UTC, merged